# https://www.schoolofnet.com/forum/topico/volumes-nao-estao-sendo-compartilhados-corretamente-1438
version: "2"
services:
  web:
    image: nginx
    container_name: wpo_web
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:Z
      - ./src/site:/home/nginx
    networks:
        - wponet
networks:
  wponet:
    driver: bridge
