package xyz.configs;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.http.HttpMethod;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;


@Configuration
@EnableWebSecurity
@Profile("production")
public class ProductionWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
	
	
	@Autowired
	private DataSource dataSource;
	
	@Autowired
	private TokenServiceConfig token;
	
	@Autowired
	private UserDetailsConfig service;
	
	/**
	 * Authorization
	 * 
	 * @see https://spring.io/guides/gs/securing-web/
	 */
	@Override
	protected void configure(HttpSecurity http) throws Exception {
			
//		// Basic authentication generated by framework
//		http.authorizeRequests()
//			.anyRequest()
//				.authenticated()
//					.and()
//						.httpBasic();
		
//		// antMatchers(HttpMethod.GET, "/topicos").permitAll();
		
//		// Basic authentication custom	
		 http.authorizeRequests()
//		 	.antMatchers("/api/**").permitAll()
		 	.antMatchers(HttpMethod.POST, "/api/login").permitAll()
		 	.antMatchers("/login/**").permitAll()
		 	.antMatchers(HttpMethod.DELETE,  "/api/topics/*").hasRole("ADMIN")
		 	.antMatchers("/actuator/**").permitAll()
			.anyRequest().authenticated()
				.and()
					.csrf().disable()
					// Disable session support
					.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
					
					.and().addFilterBefore(new OnePerRequestFilterConfig(token), UsernamePasswordAuthenticationFilter.class);	
//					.formLogin();
//					.formLogin(form -> {
//						form.loginPage("/login")
//							.defaultSuccessUrl("/", true)
//							.permitAll();
//					})
//					.logout(logout -> logout.logoutUrl("/logout"))
//					.csrf().disable();		
	}
	
	/**
	 * Authentication
	 */
	@Override
	protected void configure(AuthenticationManagerBuilder builder) throws Exception {
		
		BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
		
		builder.userDetailsService(this.service)
			.passwordEncoder(encoder);
		
		

//		
//		// Creating new user for start
//		UserDetails user = User.builder()
//				.username("admin")
//				.password(encoder.encode("admin"))
//				.roles("ADM")
//				.build();
//		
//		builder.jdbcAuthentication()
//			.dataSource(this.dataSource)
//			.passwordEncoder(encoder);
//			.withUser(user);
	}

	/**
	 * Static Resource
	 */	
	@Override
	public void configure(WebSecurity web) throws Exception {

		super.configure(web);
	}
	
	@Override
	@Bean
	protected AuthenticationManager authenticationManager() throws Exception {
		return super.authenticationManager();
	}

//	@Bean
//	@Override
//	public UserDetailsService userDetailsService() {
//		
//		UserDetails user = User.withDefaultPasswordEncoder()
//			.username("admin")
//			.password("admin")
//			.roles("ADM")
//			.build();
//
//		return new InMemoryUserDetailsManager(user);
//	}
}
