package xyz.configs;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;


@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
	
	
	@Autowired
	private DataSource dataSource;
	
	/**
	 * 
	 * @see https://spring.io/guides/gs/securing-web/
	 */
	@Override
	protected void configure(HttpSecurity http) throws Exception {
			
//		ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry a1 = http.authorizeRequests();	
//		ExpressionUrlAuthorizationConfigurer<HttpSecurity>.AuthorizedUrl a2 = a1.anyRequest();
//		ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry a3 = a2.authenticated();
//		HttpSecurity a4 = a3.and();
//		FormLoginConfigurer<HttpSecurity> a5 = a4.formLogin();		
		
		
//		// Basic authentication generated by framework
//		http.authorizeRequests()
//			.anyRequest()
//				.authenticated()
//					.and()
//						.httpBasic();
		
//		// Basic authentication custom	
		 http.authorizeRequests()
		 	.antMatchers("/api/**")
		 		.permitAll()
			.anyRequest()
				.authenticated()
					.and()
						.formLogin(form -> {
							form.loginPage("/login")
								.defaultSuccessUrl("/", true)
								.permitAll();
						})
						.logout(logout -> logout.logoutUrl("/logout"))
						.csrf().disable();
//		// you shall create GET "/login" in same controller to show custom form 
		
	}
	
	@Override
	protected void configure(AuthenticationManagerBuilder builder) throws Exception {
		
		BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
		
//		// Creating new user for start
//		UserDetails user = User.builder()
//				.username("admin")
//				.password(encoder.encode("admin"))
//				.roles("ADM")
//				.build();
		
		builder.jdbcAuthentication()
			.dataSource(this.dataSource)
			.passwordEncoder(encoder);
//			.withUser(user);
	}

//	@Bean
//	@Override
//	public UserDetailsService userDetailsService() {
//		
//		UserDetails user = User.withDefaultPasswordEncoder()
//			.username("admin")
//			.password("admin")
//			.roles("ADM")
//			.build();
//
//		return new InMemoryUserDetailsManager(user);
//	}
}
